server/login/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url('regist_user', views.RegistUser.as_view(), name='regist_user'),
    url('app_login', views.AppLogin.as_view(), name='app_login'),
    url('logout', views.LogOut.as_view(), name='logout'),
]

server/qnaboard/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from qnaboard.views import *

# . :햔재폴더 - noticeboard

app_name = 'qnaboard'
urlpatterns = [
    path('', views.index, name='index'),
    # <a class ="cls1" href="{% url 'noticeboard:write_article' $}"></a>
    # 위 코드에서 name = 'write_article'이 호출되면, path 맨앞 아규먼트 'write'의 주소로 보내지는것
    # 이러면 주소가바뀌어도 쉽게고칠수있다.
    path('write', views.write_article, name='write_article'),

    # 글내용보내는기능 링크.
    path('add', views.add_article, name='add_article'),

    # 아이디 번호를 받아오기때문에 <int:article_id>/' 로 받는다.
    path('<int:article_id>/', views.view_article, name='view'),

    # 글수정
    path('update/<int:article_id>/', views.update_article, name='update'),
    path('delete/<int:article_id>/', views.delete_article, name='delete'),

    #글쓰기(안드로이드)
    url('regist_qna', views.RegistQna.as_view(), name='regist_qna'),

]

server/testpj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('httpTest/',include('httpTest.urls')),
    path('login/',include('login.urls')),
    path('qnaboard/', include('qnaboard.urls')),
    #path('qnaboard/', include('qnaboard.urls')),
    #path('img_processing/', views.image_upload_view, name='img_process'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/qnaboard/models.py
from django.db import models
from django.utils.timezone import now


# Create your models here.
class Qna(models.Model):

    # models.Model 을 무조건 상속하게해야함
    # 요소가 컬럼이된다

    # title varchar(100)
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=2000)
    writeDate = models.DateTimeField(default=now, editable=False)
    writeID = models.CharField(max_length=50)
    receiveEmail = models.CharField(max_length=100)
    # 별도로 프라이머리키 생성하지않으면 ID 라는 이름으로 자동으로 키 생성해줌

    def __str__(self):
        return self.title


    #class Meta:
     #   db_table = 'Qna'

server/qnaboard/views.py
from django.shortcuts import render, get_object_or_404
from qnaboard.models import Qna
from login.models import User
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from rest_framework.views import APIView
from rest_framework.response import Response


# Create your views here.

# 사용자가 요구한 리퀘스트객체받음.
def index(request):
    article_list = Qna.objects.all().order_by('-writeDate')
    # Notice.object 안에 있는 걸 모두갖고옴
    # select all 같은거임.
    # 그런데 writeDate를 기준으로 -(디센딩)해서 정렬해서 갖고와라.

    # 받아온 데이터를 컨텍스트에 딕셔너리 형태로저장
    context = {'article_list': article_list}

    return render(request, 'qnaboard/index.html', context)


# 글쓰기함수
def write_article(request):
    # 별 기능 없고 글쓰기쪽으로 쏴주기만하는기능
    return render(request, 'qnaboard/writeArticle.html')


# 글내용보내는함수
def add_article(request):
    print(request.session.get('user_id', 'unknown'))
    qna = Qna()
    user = User()
    # 매개변수 request 에서 POST로 받아온것중 '키값'인것
    qna.title = request.POST['title']
    qna.content=request.POST['content']
    qna.writeID=request.session.get('user_id', 'unknown')
    qna.receiveEmail=request.POST['email']

    # 위에서 받아온 값 저장.
    qna.save()

    # 특정 사이트로 호출하라고 보내는것이 리다이렉트임.(현재앱에서 다른앱으로가는거
    # 탬플릿 랭기지에잇는 url을 파이썬으로만들어놓은것이 reverse
    return HttpResponseRedirect(reverse('qnaboard:index'))


# get_object_or_404 : 있으면 Notice가져옴, 없으면 404 낫파운드 화면을 사용자에게 뿌려줌
def view_article(request, article_id):
    qna= get_object_or_404(Qna,pk=article_id)
    #항상 딕셔너리 타입으로 보내줘야해서 즉석에서만듬
    return render(request, 'qnaboard/detail.html', {'article':qna} )


# 글수정
def update_article(request, article_id):
    # notice= get_object_or_404(Notice,pk=article_id) 하지않은이유:
    # 당연히 있는 걸 가져왔기 때문에 굳이하지않는다.
    qna = Qna.objects.get(id=article_id)
    if request.method == 'POST':
        # 주소창에 수동타이핑으로 입력해서 들어온경우를 방지하기 위함
        qna.title = request.POST['title']
        # title : name의 값임. (name='title')
        qna.content = request.POST['content']
        qna.title = request.POST['title']
        qna.writeDate = timezone.datetime.now()
        qna.save()
        return HttpResponseRedirect(reverse('qnaboard:view', args=(article_id,)))
        # 파이썬의 튜플은 원소가 하나인경우에는 반드시 콤마를 붙여줘야 튜플로 인식이된다. (article_id,)
    else:
        return render(request, 'qnaboard/detail.html', {'article': qna})


def delete_article(request, article_id):
    qna = Qna.objects.get(id=article_id)
    qna.delete()
    # 전체리스트 보여줌.
    return HttpResponseRedirect(reverse('qnaboard:index'))

class RegistQna(APIView):
    def post(self, request):

        title = request.data['title']
        email = request.data['email']
        content = request.data['content']
        # 공백 체크
        if (email == '' or None) or (title == '' or None) or (content == '' or None):
            return Response(status=200, data=dict(msg="제목,이메일,내용을 채워주세요"))
        writeID = request.session.get('user_id', 'UNKNOWN')

        # 집어넣기
        qna = Qna.objects.create(title=title, receiveEmail =email , content=content, writeID=writeID)

        return Response(status=200, data=dict(msg="등록 성공"))

server/templates/qnaboard/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>글보기</title>
    <style>
        #tr_btn_modify {
            display:none;
        }
    </style>
    <script>
        function backToList(obj){
            obj.action="{% url 'qnaboard:index' %}";
            obj.submit();
        }
        function fn_enable(obj){
            //제목과 내용만 수정가능
            document.querySelector('#i_title').disabled = false;
            document.querySelector('#i_content').disabled = false;
            document.querySelector('#tr_btn_modify').style.display = "block";
            document.querySelector('#tr_btn').style.display = "none";
        }

        function fn_modify_article(obj){
            obj.action="{% url 'qnaboard:update' article.id %}";
            obj.submit();
        }

        function fn_remove_article(obj){
            obj.action="{% url 'qnaboard:delete' article.id %}";
            obj.submit();
        }
    </script>
</head>
<body>
    <form name="frmArticle" method="post">
        {% csrf_token %}
        <table border="0" align="center">
            <tbody>
                <tr>
                    <td width="150" align="center" bgcolor="#FF993">글번호</td>
                    <td><input type="text" value="{{article.id}}" disabled></td>
                </tr>
                <tr>
                    <td width="150" align="center" bgcolor="#FF993">작성자 email</td>
                    <td><input type="text" value="{{article.receiveEmail}}" name="writer" disabled></td>
                </tr>
                <tr>
                    <td width="150" align="center" bgcolor="#FF993">제목</td>
                    <td><input type="text" value="{{article.title}}" name="title" id="i_title" disabled></td>
                </tr>
                <tr>
                    <td width="150" align="center" bgcolor="#FF993">내용</td>
                    <td><textarea rows="20" cols="60" name="content" id="i_content" disabled>{{article.content}}</textarea></td>
                </tr>
                <tr>
                    <td width="20%" align="center" bgcolor="#FF993">등록일자</td>
                    <td><input type="text" value="{{article.writeDate}}" disabled></td>
                </tr>
                <tr id="tr_btn_modify">
                    <td colspan="2" align="center">
                        <input type="button" value="수정반영하기" onclick="fn_modify_article(frmArticle)">
                        <input type="button" value="취소" onclick="backToList(frmArticle)">
                    </td>
                </tr>
                <tr id="tr_btn">
                    <td colspan="2" align="center">
                        <!--<input type="button" value="수정하기" onclick="fn_enable(frmArticle)">-->
                        <input type="button" value="삭제하기" onclick="fn_remove_article(frmArticle)">
                        <input type="button" value="리스트로 돌아가기" onclick="backToList(frmArticle)">
                    </td>
                </tr>
            </tbody>
        </table>
    </form>
</body>
</html>

server/templates/qnaboard/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>게시글 목록</title>
    <style>
        .cls1 {
            text-decoration: none;
        }
        .cls2 {
            text-align: center;
            font-size: 30px;
            display: block;
        }
    </style>
</head>
<body>
    <table align="center" border="1" width="80%">
        <thead>
            <tr height = "10" align="center" bgcolor="lightgreen">
                <th>글번호</th>
                <!--<th>작성자</th>-->
                <th>제목</th>
                <th>작성일</th>
            </tr>
        </thead>
        <!-- 그 키 이름으로 데이터가 존재한다면? , 아티클 리스트에 데이타가 있으면-->
        {%if article_list %}
        <tbody>
            {% for article in article_list %}
                <tr align = "center">
                    <!-- forloop.counter : 장고 템플릿 랭귀지에서 지원해주는 for 루프 횟수뽑아주는함수
                        장고에서 변수 표현법 : {{변수}} 중괄호두개-->
                    <!-- 게시글번호 -->
                    <td width = "5%">{{forloop.counter}}</td>
                    <!-- 작성자 
                    <td width = "10%">{{article.writeID}}</td>-->
                    <!-- 제목-->
                    <td align= "left" width = "35%">
                        <span style="padding-right:30px"></span>
                        <a class = "cls1" href="{% url 'qnaboard:view' article.id %}">{{article.title}}</a>
                    </td>
                    <!-- 글작성시간 -->
                    <td width = 10%>{{article.writeDate}}</td>
                </tr>
            {% endfor%}
        </tbody>
        {%else%}
        <tbody>
            <!-- 데이터가 존재하지않을때. 없을때 else 처리-->
            <tr height="10">
                <td colspan="4">
                    <p align="center">
                        <b><span sytle="font-size:15px;">등록된 글이 없습니다.</span></b>
                    </p>
                </td>
            </tr>
        </tbody>
        {%endif%}
    </table>
<!-- href 에 직접 주소를 쓰는것보다 urls에 명시된 네임으로 걸어준닷-->
    <a class ="cls1" href="{% url 'qnaboard:write_article' %}">
        <!--<span class ="cls2">글쓰기</span>-->
    </a>
</body>
</html>

server/templates/qnaboard/writeArticle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>새 글 쓰기</title>

    <script>
    //뒤로가기
        function backToList(obj){
        //노티스보드.인덱스로보낸다.
            obj.action="{% url 'qnaboard:index' %}";
            obj.submit();
        }
    </script>
</head>
<body>
    <h1 style = "text-align:center"> 문의 글 쓰기</h1>
    <hr>
    <!-- action: 실제 url 주소 필요. 어디로보낼건지.-->
		<!-- 실행되지않으면 아랫줄 action="{% url 'qnaboard:add_article' %}" 일시제거.-->
    <form name = "articleForm" method="post" action="{% url 'qnaboard:add_article' %}">
        {% csrf_token %} <!-- 폼 태그만들었을때 토큰을 꼭 넣어줘야함, (보안상의문제. 내가보내는것이라고확인하는용.)-->
        <table border="0" align="center">
            <tbody>
            <!--글제목-->
                <tr>
                    <td align="right">글제목:</td>
                    <td colspan="2"><input type="text" size="60" maxlength="100" name="title"/></td>
                </tr>
            <!-- 이메일-->
              <tr>
                    <td align="right">수신받을 email:</td>
                    <td colspan="2"><input type="text" size="60" maxlength="100" name="email"/></td>
                </tr>
            <!--글내용-->
                <tr>
                    <td align="right" valign="top"><br>글내용:</td>
                    <td colspan="2"><textarea name="content" rows="10" cols="65" maxlength="2000"></textarea> </td>
                </tr>
            <!--글쓰기, 뒤로가기 버튼-->
                <tr>
                    <td align="right"></td>
                    <td colspan="2">
                        <input type="submit" value="글쓰기"/>
                        <input type="button" value="목록보기" onclick="backToList(this.form)"/></td>
                    </td>

                </tr>
            </tbody>
        </table>
    </form>
</body>
</html>